// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace TraineAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230417073502_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entites.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("Entites.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CommentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("Entites.Models.LiveLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfShareLoaction")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.HasIndex("UserId");

                    b.ToTable("liveLocations");
                });

            modelBuilder.Entity("Entites.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("ContentOfPost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("news");
                });

            modelBuilder.Entity("Entites.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardNumber")
                        .HasColumnType("int");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("Entites.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PostId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Critical")
                        .HasColumnType("bit");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("UserId");

                    b.ToTable("posts");
                });

            modelBuilder.Entity("Entites.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReportId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descreption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("Entites.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainId");

                    b.ToTable("stations");

                    b.HasData(
                        new
                        {
                            Id = 11145600,
                            Description = "Alexandria is the second capital of Egypt and was its capital in the past. It is the capital of Alexandria Governorate and its largest city, located on the Mediterranean coast.",
                            Latitude = 31.193105781485116,
                            Longitude = 29.905233139369273,
                            Name = "Alexandria",
                            NextStation = "Sidi Gaber",
                            TrainId = 164
                        },
                        new
                        {
                            Id = 11225600,
                            Description = "Sidi Gaber district; It is one of the high-end neighborhoods and areas in Alexandria, Egypt.",
                            Latitude = 31.218776152059611,
                            Longitude = 29.942300551565349,
                            Name = "Sidi Gaber",
                            NextStation = "Damanhour",
                            TrainId = 164
                        },
                        new
                        {
                            Id = 10100120,
                            Description = "The Al-Tawbah Mosque is located in it, and it is the second mosque in Africa that was built by Amr bin Al-Aas in the year 21 AH.",
                            Latitude = 31.034533770853649,
                            Longitude = 30.468689104431753,
                            Name = "Damanhour",
                            NextStation = "Tanta",
                            TrainId = 164
                        },
                        new
                        {
                            Id = 1145100,
                            Description = "The College of the Holy Qur’an (Tanta) is the first of its kind at Al-Azhar University, and it has no equal in terms of its specialization in the Holy Qur’an except for the College of the Holy Qur’an in Medina. The origin of the reciter, Sheikh Mahmoud Khalil Al-Husri.",
                            Latitude = 30.781941029218899,
                            Longitude = 30.995483984834241,
                            Name = "Tanta",
                            NextStation = "Birket el Sab",
                            TrainId = 164
                        },
                        new
                        {
                            Id = 14514520,
                            Description = "One of the facilities of the General Authority for Culture Palaces is the House of Culture in Birket El Sab.",
                            Latitude = 30.637454507182532,
                            Longitude = 31.079936683751335,
                            Name = "Birket El Sab",
                            NextStation = "Qewaisna",
                            TrainId = 164
                        },
                        new
                        {
                            Id = 14512002,
                            Description = "There is a war road in Quesna, and this road was used during the war to transport equipment and ammunition. The Delta University of Technology was established in 2019 in Quesna and includes four majors in the field of technology.",
                            Latitude = 30.547991778887262,
                            Longitude = 31.139919904419259,
                            Name = "Qewaisna",
                            NextStation = "Banha",
                            TrainId = 164
                        },
                        new
                        {
                            Id = 14512345,
                            Description = "It is called Banha Al - Assal as it produces the finest types of bee honey.",
                            Latitude = 30.455953488998389,
                            Longitude = 31.181093848594685,
                            Name = "Banha",
                            NextStation = "Ramsis(Cairo)",
                            TrainId = 164
                        },
                        new
                        {
                            Id = 14512400,
                            Description = "Cairo is ranked 35th as the longest metro line among 114 cities in the world.",
                            Latitude = 30.063231628191652,
                            Longitude = 31.246724130095895,
                            Name = "Ramsis(Cairo)",
                            NextStation = "nextStation",
                            TrainId = 164
                        },
                        new
                        {
                            Id = 145124505,
                            Description = "Alexandria is the second capital of Egypt and was its capital in the past. It is the capital of Alexandria Governorate and its largest city, located on the Mediterranean coast.",
                            Latitude = 31.193105781485116,
                            Longitude = 29.905233139369273,
                            Name = "Alexandria",
                            NextStation = "Sidi Gaber",
                            TrainId = 914
                        },
                        new
                        {
                            Id = 14510534,
                            Description = "Sidi Gaber district; It is one of the high-end neighborhoods and areas in Alexandria, Egypt.",
                            Latitude = 31.218776152059611,
                            Longitude = 29.942300551565349,
                            Name = "Sidi Gaber",
                            NextStation = "Damanhour",
                            TrainId = 914
                        },
                        new
                        {
                            Id = 145123487,
                            Description = "The Al-Tawbah Mosque is located in it, and it is the second mosque in Africa that was built by Amr bin Al-Aas in the year 21 AH.",
                            Latitude = 31.034533770853649,
                            Longitude = 30.468689104431753,
                            Name = "Damanhour",
                            NextStation = "Itay El Barud",
                            TrainId = 914
                        },
                        new
                        {
                            Id = 1045452120,
                            Description = "The origin of Sheikh Muhammad Al-Ghazali.",
                            Latitude = 30.887954013325928,
                            Longitude = 30.67008637907707,
                            Name = "Itay El Barud",
                            NextStation = "Kafr El-Zayat",
                            TrainId = 914
                        },
                        new
                        {
                            Id = 10405120,
                            Description = "The opening of the Welcome Ramadan exhibition in Kafr El-Zayyat to provide food commodities to citizens 2023.",
                            Latitude = 30.81945162969096,
                            Longitude = 30.814538865795129,
                            Name = "Kafr El-Zayat",
                            NextStation = "Tanta",
                            TrainId = 914
                        },
                        new
                        {
                            Id = 145114580,
                            Description = "The College of the Holy Qur’an (Tanta) is the first of its kind at Al-Azhar University, and it has no equal in terms of its specialization in the Holy Qur’an except for the College of the Holy Qur’an in Medina. The origin of the reciter, Sheikh Mahmoud Khalil Al-Husri.",
                            Latitude = 30.781941029218899,
                            Longitude = 30.995483984834241,
                            Name = "Tanta",
                            NextStation = "Birket el Sab",
                            TrainId = 914
                        },
                        new
                        {
                            Id = 145127400,
                            Description = "One of the facilities of the General Authority for Culture Palaces is the House of Culture in Birket El Sab.",
                            Latitude = 30.637454507182532,
                            Longitude = 31.079936683751335,
                            Name = "Birket El Sab",
                            NextStation = "Qewaisna",
                            TrainId = 914
                        },
                        new
                        {
                            Id = 145127445,
                            Description = "There is a war road in Quesna, and this road was used during the war to transport equipment and ammunition. The Delta University of Technology was established in 2019 in Quesna and includes four majors in the field of technology.",
                            Latitude = 30.547991778887262,
                            Longitude = 31.139919904419259,
                            Name = "Qewaisna",
                            NextStation = "Banha",
                            TrainId = 914
                        },
                        new
                        {
                            Id = 1478913620,
                            Description = "It is called Banha Al - Assal as it produces the finest types of bee honey.",
                            Latitude = 30.455953488998389,
                            Longitude = 31.181093848594685,
                            Name = "Banha",
                            NextStation = "Ramsis(Cairo)",
                            TrainId = 914
                        },
                        new
                        {
                            Id = 1004875120,
                            Description = "Cairo is ranked 35th as the longest metro line among 114 cities in the world.",
                            Latitude = 30.063231628191652,
                            Longitude = 31.246724130095895,
                            Name = "Ramsis(Cairo)",
                            NextStation = "nextStation",
                            TrainId = 914
                        },
                        new
                        {
                            Id = 1331520,
                            Description = "Alexandria is the second capital of Egypt and was its capital in the past. It is the capital of Alexandria Governorate and its largest city, located on the Mediterranean coast.",
                            Latitude = 31.193105781485116,
                            Longitude = 29.905233139369273,
                            Name = "Alexandria",
                            NextStation = "Sidi Gaber",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 130313120,
                            Description = "Sidi Gaber district; It is one of the high-end neighborhoods and areas in Alexandria, Egypt.",
                            Latitude = 31.218776152059611,
                            Longitude = 29.942300551565349,
                            Name = "Sidi Gaber",
                            NextStation = "Kafr El Dawwar",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 105433120,
                            Description = "Misr Spinning and Weaving Company in Kafr El-Dawar is the largest company in the city, and it comes in second place in Egypt after Misr Spinning and Weaving Company in El-Mahalla El-Kubra.",
                            Latitude = 31.132741286101705,
                            Longitude = 30.130901427172223,
                            Name = " Kafr El Dawwar",
                            NextStation = "Abu Humus",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 1331201210,
                            Description = "Among the archaeological monuments in the Abu Hummus center is Tel Koum Archaeological Center, which is an area where there are likely to be antiquities, and it is located south of Ezbet El Sawy.",
                            Latitude = 31.085098233708155,
                            Longitude = 30.310392025322059,
                            Name = "Abu Humus",
                            NextStation = "Damanhour",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 1303202120,
                            Description = "The Al-Tawbah Mosque is located in it, and it is the second mosque in Africa that was built by Amr bin Al-Aas in the year 21 AH.",
                            Latitude = 31.034533770853649,
                            Longitude = 30.468689104431753,
                            Name = "Damanhour",
                            NextStation = "Itay El Barud",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 15132120,
                            Description = "The origin of Sheikh Muhammad Al-Ghazali.",
                            Latitude = 30.887954013325928,
                            Longitude = 30.67008637907707,
                            Name = "Itay El Barud",
                            NextStation = "Tawfiqia",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 18821230,
                            Description = "Al Tawfiqia Hospital is located on the agricultural road and serves all road accidents from Tanta to Kafr El Dawwar.",
                            Latitude = 30.816339320978063,
                            Longitude = 30.748217873741716,
                            Name = "Tawfiqia",
                            NextStation = "Kafr El-Zayat",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 18872121,
                            Description = "The opening of the Welcome Ramadan exhibition in Kafr El-Zayyat to provide food commodities to citizens 2023.",
                            Latitude = 30.81945162969096,
                            Longitude = 30.814538865795129,
                            Name = "Kafr El-Zayat",
                            NextStation = "Tanta",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 1821021,
                            Description = "The College of the Holy Qur’an (Tanta) is the first of its kind at Al-Azhar University, and it has no equal in terms of its specialization in the Holy Qur’an except for the College of the Holy Qur’an in Medina. The origin of the reciter, Sheikh Mahmoud Khalil Al-Husri.",
                            Latitude = 30.781941029218899,
                            Longitude = 30.995483984834241,
                            Name = "Tanta",
                            NextStation = "Birket el Sab",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 11723120,
                            Description = "One of the facilities of the General Authority for Culture Palaces is the House of Culture in Birket El Sab.",
                            Latitude = 30.637454507182532,
                            Longitude = 31.079936683751335,
                            Name = "Birket El Sab",
                            NextStation = "Qewaisna",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 182154220,
                            Description = "There is a war road in Quesna, and this road was used during the war to transport equipment and ammunition. The Delta University of Technology was established in 2019 in Quesna and includes four majors in the field of technology.",
                            Latitude = 30.547991778887262,
                            Longitude = 31.139919904419259,
                            Name = "Qewaisna",
                            NextStation = "Banha",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 210212210,
                            Description = "It is called Banha Al - Assal as it produces the finest types of bee honey.",
                            Latitude = 30.455953488998389,
                            Longitude = 31.181093848594685,
                            Name = "Banha",
                            NextStation = "Toukh",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 2102120,
                            Description = "The center and city of Toukh, in the center of Qalyubia Governorate. It is one of the ancient villages.",
                            Latitude = 30.351615440389189,
                            Longitude = 31.198362936947632,
                            Name = "Toukh",
                            NextStation = "Qaha",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 201021020,
                            Description = "Qaha Preserved Food Company is an Egyptian government joint stock company, owned by the Holding Company for Food Industries, one of the companies of the Ministry of Supply and Internal Trade, working in the field of food industries.",
                            Latitude = 30.285198657390623,
                            Longitude = 31.208928538794947,
                            Name = "Qaha",
                            NextStation = "Shubra El Kheima",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 24052120,
                            Description = "Shubra El Kheima, a suburb of Cairo. Originally, I was known by the names of Shubra al-Shaheed and Shubra al-Balad, and I was also known as Shubra Damanhour, after the city next to it called Damanhour.",
                            Latitude = 30.122241959951801,
                            Longitude = 31.244513237455582,
                            Name = "Shubra El Kheima",
                            NextStation = "nextStation",
                            TrainId = 18
                        },
                        new
                        {
                            Id = 33021020,
                            Description = "Alexandria is the second capital of Egypt and was its capital in the past. It is the capital of Alexandria Governorate and its largest city, located on the Mediterranean coast.",
                            Latitude = 31.193105781485116,
                            Longitude = 29.905233139369273,
                            Name = "Alexandria",
                            NextStation = "Sidi Gaber",
                            TrainId = 916
                        },
                        new
                        {
                            Id = 3302120,
                            Description = "Sidi Gaber district; It is one of the high-end neighborhoods and areas in Alexandria, Egypt.",
                            Latitude = 31.218776152059611,
                            Longitude = 29.942300551565349,
                            Name = "Sidi Gaber",
                            NextStation = "Ramsis(Cairo)",
                            TrainId = 916
                        },
                        new
                        {
                            Id = 33021101,
                            Description = "Cairo is ranked 35th as the longest metro line among 114 cities in the world.",
                            Latitude = 30.063231628191652,
                            Longitude = 31.246724130095895,
                            Name = "Ramsis(Cairo)",
                            NextStation = "nextStation",
                            TrainId = 916
                        },
                        new
                        {
                            Id = 330211203,
                            Description = "Alexandria is the second capital of Egypt and was its capital in the past. It is the capital of Alexandria Governorate and its largest city, located on the Mediterranean coast.",
                            Latitude = 31.193105781485116,
                            Longitude = 29.905233139369273,
                            Name = "Alexandria",
                            NextStation = "Sidi Gaber",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 303021200,
                            Description = "Sidi Gaber district; It is one of the high-end neighborhoods and areas in Alexandria, Egypt.",
                            Latitude = 31.218776152059611,
                            Longitude = 29.942300551565349,
                            Name = "Sidi Gaber",
                            NextStation = "Kafr El Dawwar",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 302002120,
                            Description = "Misr Spinning and Weaving Company in Kafr El-Dawar is the largest company in the city, and it comes in second place in Egypt after Misr Spinning and Weaving Company in El-Mahalla El-Kubra.",
                            Latitude = 31.132741286101705,
                            Longitude = 30.130901427172223,
                            Name = " Kafr El Dawwar",
                            NextStation = "Abu Humus",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 330302120,
                            Description = "Among the archaeological monuments in the Abu Hummus center is Tel Koum Archaeological Center, which is an area where there are likely to be antiquities, and it is located south of Ezbet El Sawy.",
                            Latitude = 31.085098233708155,
                            Longitude = 30.310392025322059,
                            Name = "Abu Humus",
                            NextStation = "Damanhour",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 404002120,
                            Description = "The Al-Tawbah Mosque is located in it, and it is the second mosque in Africa that was built by Amr bin Al-Aas in the year 21 AH.",
                            Latitude = 31.034533770853649,
                            Longitude = 30.468689104431753,
                            Name = "Damanhour",
                            NextStation = "Itay El Barud",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 45021020,
                            Description = "The origin of Sheikh Muhammad Al-Ghazali.",
                            Latitude = 30.887954013325928,
                            Longitude = 30.67008637907707,
                            Name = "Itay El Barud",
                            NextStation = "Tawfiqia",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 125021020,
                            Description = "Al Tawfiqia Hospital is located on the agricultural road and serves all road accidents from Tanta to Kafr El Dawwar.",
                            Latitude = 30.816339320978063,
                            Longitude = 30.748217873741716,
                            Name = "Tawfiqia",
                            NextStation = "Kafr El-Zayat",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 451021020,
                            Description = "The opening of the Welcome Ramadan exhibition in Kafr El-Zayyat to provide food commodities to citizens 2023.",
                            Latitude = 30.81945162969096,
                            Longitude = 30.814538865795129,
                            Name = "Kafr El-Zayat",
                            NextStation = "Tanta",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 45002129,
                            Description = "The College of the Holy Qur’an (Tanta) is the first of its kind at Al-Azhar University, and it has no equal in terms of its specialization in the Holy Qur’an except for the College of the Holy Qur’an in Medina. The origin of the reciter, Sheikh Mahmoud Khalil Al-Husri.",
                            Latitude = 30.781941029218899,
                            Longitude = 30.995483984834241,
                            Name = "Tanta",
                            NextStation = "Birket el Sab",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 99021020,
                            Description = "One of the facilities of the General Authority for Culture Palaces is the House of Culture in Birket El Sab.",
                            Latitude = 30.637454507182532,
                            Longitude = 31.079936683751335,
                            Name = "Birket El Sab",
                            NextStation = "Qewaisna",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 90902120,
                            Description = "There is a war road in Quesna, and this road was used during the war to transport equipment and ammunition. The Delta University of Technology was established in 2019 in Quesna and includes four majors in the field of technology.",
                            Latitude = 30.547991778887262,
                            Longitude = 31.139919904419259,
                            Name = "Qewaisna",
                            NextStation = "Banha",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 45002450,
                            Description = "It is called Banha Al - Assal as it produces the finest types of bee honey.",
                            Latitude = 30.455953488998389,
                            Longitude = 31.181093848594685,
                            Name = "Banha",
                            NextStation = "Toukh",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 413020120,
                            Description = "The center and city of Toukh, in the center of Qalyubia Governorate. It is one of the ancient villages.",
                            Latitude = 30.351615440389189,
                            Longitude = 31.198362936947632,
                            Name = "Toukh",
                            NextStation = "Qaha",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 21200,
                            Description = "Qaha Preserved Food Company is an Egyptian government joint stock company, owned by the Holding Company for Food Industries, one of the companies of the Ministry of Supply and Internal Trade, working in the field of food industries.",
                            Latitude = 30.285198657390623,
                            Longitude = 31.208928538794947,
                            Name = "Qaha",
                            NextStation = "Qelyoub",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 212022,
                            Description = "Among the Islamic monuments is Al-Zahir Baybars Mosque, which was built in the year 670-672 AH in the village of Qalyub.",
                            Latitude = 30.187796088125985,
                            Longitude = 31.22807432746081,
                            Name = "Qelyoub",
                            NextStation = "Shubra El Kheima",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 2018020,
                            Description = "Shubra El Kheima, a suburb of Cairo. Originally, I was known by the names of Shubra al-Shaheed and Shubra al-Balad, and I was also known as Shubra Damanhour, after the city next to it called Damanhour.",
                            Latitude = 30.122241959951801,
                            Longitude = 31.244513237455582,
                            Name = "Shubra El Kheima",
                            NextStation = "nextStation",
                            TrainId = 24
                        },
                        new
                        {
                            Id = 188120,
                            Description = "description",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "name",
                            NextStation = "nextStation",
                            TrainId = 0
                        });
                });

            modelBuilder.Entity("Entites.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfSeat")
                        .HasColumnType("int");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("ScanedOrNot")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TakeOffDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TakeOffStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainDegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("Entites.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrainId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conductor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Driver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfSeat")
                        .HasColumnType("int");

                    b.Property<int>("NumOfTrainCars")
                        .HasColumnType("int");

                    b.Property<string>("TrainNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trains");

                    b.HasData(
                        new
                        {
                            Id = 164,
                            Conductor = "",
                            CurrentLocation = "",
                            Degree = "3rd Air Conditioned",
                            Driver = "",
                            NumOfSeat = 880,
                            NumOfTrainCars = 11,
                            TrainNumber = "164"
                        },
                        new
                        {
                            Id = 914,
                            Conductor = "",
                            CurrentLocation = "",
                            Degree = "1st & 2nd Air Conditioned",
                            Driver = "",
                            NumOfSeat = 572,
                            NumOfTrainCars = 10,
                            TrainNumber = "914"
                        },
                        new
                        {
                            Id = 18,
                            Conductor = "",
                            CurrentLocation = "",
                            Degree = "3rd Air Conditioned",
                            Driver = "",
                            NumOfSeat = 880,
                            NumOfTrainCars = 11,
                            TrainNumber = "18"
                        },
                        new
                        {
                            Id = 916,
                            Conductor = "",
                            CurrentLocation = "",
                            Degree = "VIP",
                            Driver = "",
                            NumOfSeat = 10,
                            NumOfTrainCars = 572,
                            TrainNumber = "916"
                        },
                        new
                        {
                            Id = 24,
                            Conductor = "",
                            CurrentLocation = "",
                            Degree = "Russian",
                            Driver = "",
                            NumOfSeat = 880,
                            NumOfTrainCars = 10,
                            TrainNumber = "24"
                        });
                });

            modelBuilder.Entity("Entites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("TrainId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Entites.Comment", b =>
                {
                    b.HasOne("Entites.Admin", "Admin")
                        .WithMany("comments")
                        .HasForeignKey("AdminId");

                    b.HasOne("Entites.Post", "Post")
                        .WithMany("comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entites.User", "User")
                        .WithMany("comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Models.LiveLocation", b =>
                {
                    b.HasOne("Entites.Train", "Train")
                        .WithMany("liveLocations")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entites.User", "User")
                        .WithMany("liveLocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Models.News", b =>
                {
                    b.HasOne("Entites.Admin", "Admin")
                        .WithMany("News")
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Entites.Payment", b =>
                {
                    b.HasOne("Entites.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Post", b =>
                {
                    b.HasOne("Entites.Admin", "Admin")
                        .WithMany("posts")
                        .HasForeignKey("AdminId");

                    b.HasOne("Entites.User", "User")
                        .WithMany("posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Report", b =>
                {
                    b.HasOne("Entites.Post", "Post")
                        .WithMany("reports")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entites.User", "User")
                        .WithMany("reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Station", b =>
                {
                    b.HasOne("Entites.Train", "Train")
                        .WithMany("stations")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Entites.Ticket", b =>
                {
                    b.HasOne("Entites.Payment", "payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entites.User", "User")
                        .WithMany("tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("payment");
                });

            modelBuilder.Entity("Entites.User", b =>
                {
                    b.HasOne("Entites.Station", "Station")
                        .WithMany("Users")
                        .HasForeignKey("StationId");

                    b.HasOne("Entites.Train", "Train")
                        .WithMany("users")
                        .HasForeignKey("TrainId");

                    b.Navigation("Station");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Entites.Admin", b =>
                {
                    b.Navigation("News");

                    b.Navigation("comments");

                    b.Navigation("posts");
                });

            modelBuilder.Entity("Entites.Post", b =>
                {
                    b.Navigation("comments");

                    b.Navigation("reports");
                });

            modelBuilder.Entity("Entites.Station", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entites.Train", b =>
                {
                    b.Navigation("liveLocations");

                    b.Navigation("stations");

                    b.Navigation("users");
                });

            modelBuilder.Entity("Entites.User", b =>
                {
                    b.Navigation("comments");

                    b.Navigation("liveLocations");

                    b.Navigation("posts");

                    b.Navigation("reports");

                    b.Navigation("tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
